### ISSUE TITLE
truncated label

### ISSUE THREAD

**Issue by NeomMob** [PaddleHQ/Windows-Framework#4]
![2018-02-28_19h10_30](https://user-images.githubusercontent.com/326762/36804604-5b9f4e54-1cbb-11e8-83f3-e1e899eb1bf9.png)

The label on the top truncate the first letter

**Comment by GregularExpressions** [comment]
Hey @NeomMob 

Thanks for the report, we're working on a new version of the Windows SDK at the moment - the progress of which you can keep up to date with here: https://github.com/PaddleHQ/sdk-c-sharp

Currently it is the checkout functionality and doesn't yet support licensing, trials, etc.

Greg.
